import Head from 'next/head';

import HubNavBar from '../components/HubNavBar';
import ImageHeader from '../components/ImageHeader';
import TeamMemberCard from '../components/TeamMemberCard';
import GetInTouchForm from '../components/GetInTouchForm';
import Footer from '../components/Footer';

// Import react-bootstrap components
import {
  Container,
  Row,
  Col
} from 'react-bootstrap';

import { fetchAPI, getStrapiURL } from '../lib/api';
const qs = require('qs');

const About = ({ members }) => {
  return (
    <>
      <Head>
        <title>About us - Smart Focus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <HubNavBar/>
      <ImageHeader size="sm" url="/images/banners/banner-home.jpg">
        <div className='d-flex justify-content-center align-items-center w-100' style={{height: '85%'}}>
          <h1 className='text-white text-center intro-heading d-block'>About us</h1>
        </div>
      </ImageHeader>
      <Container>
        <section>
          <h2 className='text-center mt-5 mb-3 heading-lg'>What we do</h2>
          <p className='main-lead my-3'>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat repudiandae quod debitis minima similique, tempore corporis, vero ut ex tempora distinctio consequatur odio, illo officia eum! Molestiae minima expedita enim soluta fugiat dicta atque eos, aliquid ipsam distinctio accusamus omnis voluptates voluptatum quam, ducimus deleniti ab ullam sapiente. Cupiditate earum omnis rem dolorem iusto aliquid minus necessitatibus atque, libero nisi.
          </p>
        </section>
        <section>
          <h2 className='text-center mt-5 mb-4 mb-md-5 heading-lg'>Services</h2>
          <Row className='mb-5'>
            <Col xs={12} md={6}>
            <h3 className='heading-sm'>Service A</h3>
            <p className='main-lead my-3'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga, illum aspernatur perferendis dolore, saepe atque provident officiis ut sit animi sed commodi aliquid maxime nihil! Nam aut totam eum eligendi!
            </p>
            </Col>
            <Col xs={12} md={6} className="text-end">
              <img src={"/images/services/serviceA.png"} className='img-fluid rounded'/>
            </Col>
          </Row>
          <Row className='mb-5'>
            <Col xs={12} md={6}>
              <h3 className='heading-sm'>Service B</h3>
              <p className='main-lead my-3'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga, illum aspernatur perferendis dolore, saepe atque provident officiis ut sit animi sed commodi aliquid maxime nihil! Nam aut totam eum eligendi!
              </p>
            </Col>
            <Col xs={12} md={6} className='order-md-first'>
              <img src={"/images/services/serviceB.jpg"} className='img-fluid rounded'/>
            </Col>
          </Row>
          <Row>
            <Col xs={12} md={6}>
            <h3 className='heading-sm'>Service C</h3>
            <p className='main-lead my-3'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga, illum aspernatur perferendis dolore, saepe atque provident officiis ut sit animi sed commodi aliquid maxime nihil! Nam aut totam eum eligendi!
            </p>
            </Col>
            <Col xs={12} md={6} className="text-end">
              <img src={"/images/services/serviceC.jpg"} className='img-fluid rounded'/>
            </Col>
          </Row>
        </section>
        <section>
          <h2 className='text-center mt-5 mb-4 mb-md-5 heading-lg'>The Team</h2>
          <div className='d-flex flex-wrap justify-content-evenly'>
            {members.map(member => {
              return (
                <TeamMemberCard
                  key={member.id}
                  id={member.id}
                  fullName={member.attributes.fullname}
                  occupation={member.attributes.occupation}
                  imageFilename={member.attributes.image.data ? getStrapiURL(member.attributes.image.data.attributes.url) : '/images/icons/profile-blank.png'}
                />
              );
            })}
          </div>
        </section>
        <section>
          <h2 className='text-center mt-5 mb-4 mb-md-5 heading-lg'>Come see us</h2>
          <Row>
            <Col xs={12} md={6}>
            <h3 className='heading-sm'>Smart Focus</h3>
            <p className='lead'><strong>Email:</strong> info@smartfocus.kiwi</p>
            <p className='lead'><strong>Ph:</strong> 123 456 7890</p>
            </Col>
            <Col xs={12} md={6}>
              <img src={"/images/services/serviceB.jpg"} className='img-fluid rounded text-end'/>
              <p className='lead mt-3'>Address details</p>
            </Col>
          </Row>
        </section>
      </Container>
      <Container fluid className='form-section pb-4'>
        <h2 className='text-center pt-4 mb-3 mb-md-4 heading-lg'>Get in Touch</h2>
        <GetInTouchForm/>
      </Container>
      <Footer/>
    </>
  );
}
 
export default About;

export async function getStaticProps() {
  const query = qs.stringify({
    populate: {
      image: {
        fields: ['url']
      }
    }
  }, {
    encodeValuesOnly: true,
  });
  console.log(`/team-members?${query}`)
  const members = await fetchAPI(`/team-members?${query}`);

  return {
    props: {
      members
    }
  }
}