import Head from 'next/head';

import HubNavBar from '../components/HubNavBar';
import ImageHeader from '../components/ImageHeader';
import Footer from '../components/Footer';

import ComingSoonMessage from '../components/ComingSoonMessage';

import { getStrapiURL, fetchAPI } from '../lib/api';
const qs = require('qs');

// Import react-bootstrap components
import {
  Container,
  Row,
  Col,
  Button
 } from 'react-bootstrap';

const Education = ({ global }) => {
  return (
    <>
      <Head>
        <title>Education - Smart Focus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HubNavBar logo={getStrapiURL(global.attributes.site_logo.data.attributes.url)}/>
      {
        /*
        <ImageHeader size="sm" src="/images/banners/banner-home.jpg">
          <div className='d-flex justify-content-center align-items-center w-100' style={{height: '85%'}}>
            <h1 className='text-white text-center intro-heading d-block'>Education</h1>
          </div>
        </ImageHeader>
        <Container className='pb-5'>
  
        </Container>
        <Footer logoSrc={getStrapiURL(global.attributes.site_logo.data.attributes.url)} email={global.attributes.contact_email} phone={global.attributes.phone} address={global.attributes.address}/>
        */
      }
      <ComingSoonMessage />
    </>
  );
}
 
export default Education;

export async function getStaticProps() {
  const query = qs.stringify({
    populate: '*'
  }, {
    encodeValuesOnly: true,
  });
  const global = await fetchAPI(`/global?${query}`);
  return {
    props: {
      global,
    }
  }
}