import Head from 'next/head';
import Link from 'next/link';

import HubNavBar from '../components/HubNavBar';
import ImageHeader from '../components/ImageHeader';
import TextSection from '../components/TextSection';
import ClusterCard from '../components/ClusterCard';
import ArticleCardGrid from '../components/ArticleCardGrid';
import Footer from '../components/Footer';
import { fetchAPI, getStrapiURL, sortArticlesByDate, getTop4Articles } from '../lib/api';
const qs = require('qs');

// Import react-bootstrap components
import {
  Container,
  Button
 } from 'react-bootstrap';

const Home = ({ global, home_content, research_papers, case_studies, news_events_and_podcasts }) => {
  return (
    <>
      <Head>
        <title>{home_content.attributes.introduction_heading} - Smart Focus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HubNavBar logo={getStrapiURL(global.attributes.site_logo.data.attributes.url)}/>
      <ImageHeader size="lg" src={getStrapiURL(home_content.attributes.header_image.data.attributes.url)} imgFade>
        <div className='d-flex justify-content-center align-items-center w-100' style={{height: '85%'}}>
          <div className='d-flex flex-column justify-content-center align-items-center'>
            <h1 className='text-white text-center intro-heading d-block mb-3'>{home_content.attributes.introduction_heading}</h1>
            <div className='d-flex justify-content-around' style={{maxWidth: '250px', width: '100%'}}>
              <Link href="/login" passHref><Button variant='primary' className='px-4' size='lg'>Login</Button></Link>
              <Link href="/signup" passHref><Button variant='warning' className='px-4' size='lg'>Sign up</Button></Link>
            </div>
          </div>
        </div>
      </ImageHeader>
      <Container className='pb-5'>
        {
          home_content.attributes.content.map((section) => (
            <TextSection key={section.id} heading={section.heading} text={section.text_content}/>
          ))
        }
        <h2 className='text-center mt-5 mb-5 heading-lg'>Our Current Clusters</h2>
        <div className='d-flex justify-content-evenly flex-wrap'>
          <ClusterCard name="Horticulture" imageSrc="/images/thumbnails/cluster-cards/horticultural.jpg" link="/clusters/horticultural">
            <p className='lead text-center'>
              See what we're doing in the horticultural sector.
            </p>
          </ClusterCard>
          <ClusterCard name="Environment" imageSrc="/images/thumbnails/cluster-cards/environmental.jpg" link="/clusters/environmental">
            <p className='lead text-center'>
              See what we're doing for the Environment.
            </p>
          </ClusterCard>
          <ClusterCard name="Technology" imageSrc="/images/thumbnails/cluster-cards/technology.jpg" link="/clusters/technology">
            <p className='lead text-center'>
              Learn about our current technologies.
            </p>
          </ClusterCard>
        </div>
        <h2 className='text-center mt-5 mb-5 heading-lg'>Latest Research Papers</h2>
        <ArticleCardGrid articles={research_papers}/>
        <div className='text-center mt-3'><Link href='/research-papers-and-case-studies?content=research papers' passHref><Button variant='primary' >View All</Button></Link></div>
        <h2 className='text-center mt-5 mb-5 heading-lg'>Latest Case Studies</h2>
        <ArticleCardGrid articles={case_studies}/>
        <div className='text-center mt-3'><Link href='/research-papers-and-case-studies?content=case studies' passHref><Button variant='primary' >View All</Button></Link></div>
        <h2 className='text-center mt-5 mb-5 heading-lg'>Latest News Events and Podcasts</h2>
        <ArticleCardGrid articles={news_events_and_podcasts} prefixType/>
        <div className='text-center mt-3'><Link href='/news-events-and-podcasts' passHref><Button variant='primary' >View All</Button></Link></div>
      </Container>
      <Footer logoSrc={getStrapiURL(global.attributes.site_logo.data.attributes.url)} email={global.attributes.contact_email} phone={global.attributes.phone} address={global.attributes.address}/>
    </>
  )
}

export default Home;

export async function getStaticProps() {
  const query_global = qs.stringify({
    populate: '*'
  }, {
    encodeValuesOnly: true,
  });

  const query_home = qs.stringify({
    populate: '*'
  }, {
    encodeValuesOnly: true,
  });

  const query_articles = qs.stringify({
    populate: {
      clusters: {
        fields: ['name']
      },
      thumbnail_image: {
        fields: ['url']
      }
    }
  }, {
    encodeValuesOnly: true,
  });
  
  const global = await fetchAPI(`/global?${query_global}`);

  const home_content = await fetchAPI(`/home?${query_home}`);

  const research_papers = getTop4Articles(sortArticlesByDate(await fetchAPI(`/research-papers?${query_articles}`)));

  const case_studies = getTop4Articles(sortArticlesByDate(await fetchAPI(`/case-studies?${query_articles}`)));
  
  const news = sortArticlesByDate(await fetchAPI(`/news?${query_articles}`));
  
  const events = sortArticlesByDate(await fetchAPI(`/events?${query_articles}`));
  
  const podcasts = sortArticlesByDate(await fetchAPI(`/podcasts?${query_articles}`));

  const news_events_and_podcasts = sortArticlesByDate([...news.slice(0, 2), events[0], podcasts[0]]);

  return {
    props: {
      global,
      home_content,
      research_papers,
      case_studies,
      news_events_and_podcasts
    }
  }
}
