import Head from 'next/head';

import ComingSoonMessage from '../components/ComingSoonMessage';

// Import react-bootstrap components
import {
  Container,
  Row,
  Col,
  Button
 } from 'react-bootstrap';

const Portal = () => {
  return (
    <>
      <Head>
        <title>Portal - Smart Focus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        /*
        <h1 className='text-center mt-5'>Portal</h1>
        <Container fluid>

        </Container>
        */
      }
      <ComingSoonMessage/>
    </>
  );
}
 
export default Portal;