import Head from 'next/head';

// Import react-bootstrap components
import {
  Container,
  Row,
  Col,
  Button
 } from 'react-bootstrap';

const Signup = () => {
  return (
    <>
      <Head>
        <title>Sign up - Smart Focus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-center mt-5'>Sign up</h1>
      
      <Container fluid>

      </Container>
    </>
  );
}
 
export default Signup;