import Head from 'next/head';

import HubNavBar from '../../../components/HubNavBar';
import Article from '../../../components/Article';
import Footer from '../../../components/Footer';

import { fetchAPI } from "../../../lib/api";
import { Container } from 'react-bootstrap';
const qs = require('qs');

const CaseStudyPage = ({ article, related_articles }) => {
  return (
    <>
      <Head>
        <title>{article.attributes.title} - Smart Focus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HubNavBar />
      <Article article={article} />
      <Container>
        <h2 className='text-center mt-5 mb-5 heading-lg'>Related articles</h2>
        {/*<ArticleCardGrid articles={related_articles}/>*/}
      </Container>
      <Footer/>
    </>
  );
}

export default CaseStudyPage;

export async function getStaticPaths() {
  const case_studies = await fetchAPI('/case-studies');
  const paths = case_studies.map(article => {
    return {
      params: {
        slug: article.attributes.slug
      }
    }
  });

  return {
    paths,
    fallback: false
  }
}

export async function getStaticProps({ params }) {
  const query = qs.stringify({
    populate: {
      header_image: {
        populate: '*'
      },
      thumbnail_image: {
        populate: '*'
      },
      content: {
        populate: '*'
      },
    },
    filters: {
      slug: {
        $eq: params.slug
      },
    },
  }, {
    encodeValuesOnly: true,
  });
  const request = `/case-studies?${query}`;
  console.log(request)
  const case_study = await fetchAPI(request);

  return {
    props: {
      article: case_study[0]
    }
  }
}