import Head from 'next/head';
import Link from 'next/link';

import HubNavBar from '../../components/HubNavBar';
import ImageHeader from '../../components/ImageHeader';
import Footer from '../../components/Footer';

// Import react-bootstrap components
import {
  Container,
  Row,
  Col,
  Button
 } from 'react-bootstrap';

const Clusters = () => {
  return (
    <>
      <Head>
        <title>Clusters - Smart Focus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HubNavBar/>
      <ImageHeader size="sm" url="/images/banners/banner-home.jpg">
        <div className='d-flex justify-content-center align-items-center w-100' style={{height: '85%'}}>
          <h1 className='text-white text-center intro-heading d-block'>Clusters</h1>
        </div>
      </ImageHeader>
      <Container>
        <section>
          <h2 className='text-center mt-5 mb-4 heading-lg'>What are Clusters?</h2>
          <Row className='mb-5'>
            <Col xs={12} md={6}>
              <p className='main-lead'>
                Cluster are a critical mass of interconnected businesses, suppliers and associated institutions that collaborate to solve common problems and to benefit from scale. Whilst there are different type of clusters we have chosen to form 3 cluster aligned to the capabilities within our region – Hort tech, environmental and technology.
              </p>
            </Col>
            <Col xs={12} md={6} className="text-end">
              <img src={"/images/clusters/clusters.png"} className='img-fluid' width={500} height={500} alt="clusters"/>
            </Col>
          </Row>
        </section>
        <section>
          <h2 className='text-center mt-5 mb-4 heading-lg'>Our current Clusters</h2>
          <Row className='mb-5'>
            <Col xs={12} md={6}>
              <h3 className='heading-sm'>Horticulture</h3>
              <p className='main-lead my-3'>
                We want to produce the best horticultural outcomes with minimal impact on the planet.
              </p>
              <Link href={'/clusters/horticultural'} passHref>
                <Button variant='primary' size='lg'>Learn more</Button>
              </Link>
            </Col>
            <Col xs={12} md={6} className="text-end mt-4 mt-md-0">
              <img src={"/images/clusters/horticulture.jpg"} className='img-fluid rounded' alt="hand holding dirt in a garden"/>
            </Col>
          </Row>
          <Row className='mb-5'>
            <Col xs={12} md={6}>
              <h3 className='heading-sm'>Environment</h3>
              <p className='main-lead my-3'>
                The environment is important to us. We want to make this world a better place for all.
              </p>
              <Link href={'/clusters/environmental'} passHref>
                <Button variant='primary' size='lg'>Learn more</Button>
              </Link>
            </Col>
            <Col xs={12} md={6} className='order-md-first mt-4 mt-md-0'>
              <img src={"/images/clusters/environment.jpg"} className='img-fluid rounded' alt="water dripping down off a hand onto a plant"/>
            </Col>
          </Row>
          <Row>
            <Col xs={12} md={6}>
              <h3 className='heading-sm'>Technology</h3>
              <p className='main-lead my-3'>
                Our technologies are enabling the digital revolution in food production, environmental conservation and many other areas of our lives.
              </p>
              <Link href={'/clusters/technology'} passHref>
                <Button variant='primary' size='lg'>Learn more</Button>
              </Link>
            </Col>
            <Col xs={12} md={6} className="text-end mt-4 mt-md-0">
              <img src={"/images/clusters/technology.jpg"} className='img-fluid rounded' alt="purple wavey grid"/>
            </Col>
          </Row>
        </section>
      </Container>
      <Footer/>
    </>
  );
}
 
export default Clusters;