import Head from 'next/head';
import Link from 'next/link';

import HubNavBar from '../../components/HubNavBar';
import ImageHeader from '../../components/ImageHeader';
import TextSection from '../../components/TextSection';
import Footer from '../../components/Footer';
import { fetchAPI, getStrapiURL } from '../../lib/api';
const qs = require('qs');

// Import react-bootstrap components
import {
  Container,
  Row,
  Col,
  Button
 } from 'react-bootstrap';

const Clusters = ({ global, clusters_content }) => {
  return (
    <>
      <Head>
        <title>Clusters - Smart Focus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HubNavBar logo={getStrapiURL(global.attributes.site_logo.data.attributes.url)}/>
      <ImageHeader size="sm" src={getStrapiURL(clusters_content.attributes.header_image.data.attributes.url)}>
        <div className='d-flex justify-content-center align-items-center w-100' style={{height: '85%'}}>
          <h1 className='text-white text-center intro-heading d-block'>Clusters</h1>
        </div>
      </ImageHeader>
      <Container className='pb-4'>
        {clusters_content.attributes.content.map((content, index) => (
          <TextSection key={content.id} heading={content.heading} text={content.text_content} image={index === 0 ? clusters_content.attributes.clusters_image : null}/>
        ))}
        <section className='mb-4'>
          <h2 className='text-center mt-5 mb-4 heading-lg'>Our current Clusters</h2>
          <Row className='mb-5'>
            <Col xs={12} md={6}>
              <h3 className='heading-sm'>Horticulture</h3>
              <p className='main-lead my-3'>
                We want to produce the best horticultural outcomes with minimal impact on the planet.
              </p>
              <Link href={'/clusters/horticultural'} passHref>
                <Button variant='primary' size='lg'>Learn more</Button>
              </Link>
            </Col>
            <Col xs={12} md={6} className="text-end mt-4 mt-md-0">
              <img src={"/images/clusters/horticulture.jpg"} className='img-fluid rounded' alt="hand holding dirt in a garden"/>
            </Col>
          </Row>
          <Row className='mb-5'>
            <Col xs={12} md={6}>
              <h3 className='heading-sm'>Environment</h3>
              <p className='main-lead my-3'>
                The environment is important to us. We want to make this world a better place for all.
              </p>
              <Link href={'/clusters/environmental'} passHref>
                <Button variant='primary' size='lg'>Learn more</Button>
              </Link>
            </Col>
            <Col xs={12} md={6} className='order-md-first mt-4 mt-md-0'>
              <img src={"/images/clusters/environment.jpg"} className='img-fluid rounded' alt="water dripping down off a hand onto a plant"/>
            </Col>
          </Row>
          <Row>
            <Col xs={12} md={6}>
              <h3 className='heading-sm'>Technology</h3>
              <p className='main-lead my-3'>
                Our technologies are enabling the digital revolution in food production, environmental conservation and many other areas of our lives.
              </p>
              <Link href={'/clusters/technology'} passHref>
                <Button variant='primary' size='lg'>Learn more</Button>
              </Link>
            </Col>
            <Col xs={12} md={6} className="text-end mt-4 mt-md-0">
              <img src={"/images/clusters/technology.jpg"} className='img-fluid rounded' alt="purple wavey grid"/>
            </Col>
          </Row>
        </section>
      </Container>
      <Footer logoSrc={getStrapiURL(global.attributes.site_logo.data.attributes.url)} email={global.attributes.contact_email} phone={global.attributes.phone} address={global.attributes.address}/>
    </>
  );
}
 
export default Clusters;

export async function getStaticProps() {
  const query_global = qs.stringify({
    populate: '*'
  }, {
    encodeValuesOnly: true,
  });
  const global = await fetchAPI(`/global?${query_global}`);

  const query_clusters = qs.stringify({
    populate: {
      header_image: {
        populate: '*'
      },
      clusters_image: {
        populate: '*'
      },
      content: {
        populate: '*'
      }
    }
  }, {
    encodeValuesOnly: true,
  });
  const clusters_content = await fetchAPI(`/clusters-page?${query_clusters}`);

  return {
    props: {
      global,
      clusters_content
    }
  }
}